.\"                                      Hey, EMACS: -*- nroff -*-
.\" (C) Copyright 2013-2015 Bruno Nova <brunomb.nova@gmail.com>,
.\"
.TH DRMIPS 1 "September 14, 2015"
.SH NAME
drmips \- educational MIPS simulator
.SH SYNOPSIS
.B drmips
.RI [ OPTIONS ]
.RI [ FILE ]
.br
.SH DESCRIPTION
.B DrMIPS 
is a graphical simulator of the MIPS processor to support computer architecture
teaching and learning. It is intuitive, versatile and configurable.
The simulator is available not only for personal computers but also for
Android devices, especially tablets.
.PP
This command starts the PC version of the simulator. You can pass a
.IR FILE 
as argument to open it in the simulator.
.SH OPTIONS
.TP
.B \-\-opengl
Enable OpenGL hardware acceleration.
.TP
.B \-\-no\-opengl
Disable OpenGL hardware acceleration.
.TP
.B \-h, \-\-help
Display help and exit.
.TP
.B \-\-version
Display version information and exit.
.TP
.B FILE
Optional file to open.
.SH SEE ALSO
The manuals of the simulator at:
.IR /usr/share/doc/drmips/manuals/
.PP
The page of the simulator at:
.IR http://brunonova.github.io/drmips/
