.\"                                      Hey, EMACS: -*- nroff -*-
.\" (C) Copyright 2013-2015 Bruno Nova <brunomb.nova@gmail.com>,
.\"
.TH DRMIPS 1 "14 de Setembro de 2015"
.SH NOME
drmips \- simulador educativo do MIPS
.SH SINOPSE
.B drmips
.RI [ OPÇÕES ]
.RI [ FICHEIRO ]
.br
.SH DESCRIÇÃO
O
.B DrMIPS 
é um simulador gráfico do processador MIPS para apoiar o ensino e a 
aprendizagem de arquitectura de computadores. É intuitivo, versátil e
configurável.
O simulador está disponível não só para computadores pessoais mas também para
dispositivos Android, especialmente tablets.
.PP
Este comando inicia a versão para PC do simulador. Pode passar um
.IR FICHEIRO
como argumento para o abrir no simulador.
.SH OPÇÕES
.TP
.B \-\-opengl
Activa a aceleração de hardware por OpenGL.
.TP
.B \-\-no\-opengl
Desactiva a aceleração de hardware por OpenGL.
.TP
.B \-h, \-\-help
Mostra a ajuda e sai.
.TP
.B \-\-version
Mostra informação da versão e sai.
.TP
.B FICHEIRO
Ficheiro opcional a abrir.
.SH VEJA TAMBÉM
Os manuais do simulador em:
.IR /usr/share/doc/drmips/manuals/
.PP
A página do simulador em:
.IR http://brunonova.github.io/drmips/
