# Warning: the project must be opened in Netbeans at least once for the
# makefile to work correctly!
ANT=ant
RM=rm -rf

.PHONY: all drmips clean

all: drmips

drmips:
	$(ANT)

clean:
	$(RM) build dist
