/*
    DrMIPS - Educational MIPS simulator
    Copyright (C) 2013 Bruno Nova <ei08109@fe.up.pt>

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

package org.feup.brunonova.drmips.gui;

import javax.swing.JOptionPane;

/**
 * Dialog that displays information of the program.
 * 
 * @author Bruno Nova
 */
public class DlgAbout extends javax.swing.JDialog {

	/**
	 * Creates new form DlgAbout
	 */
	public DlgAbout(FrmSimulator parent) {
		super(parent, true);
		initComponents();
		translate();
		getRootPane().setDefaultButton(cmdOk);
		Util.enableCloseWindowWithEscape(this);
		Util.centerWindow(this);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblVersion = new javax.swing.JLabel();
        lblIcon = new javax.swing.JLabel();
        lblAuthor = new javax.swing.JLabel();
        lblDissertation = new javax.swing.JLabel();
        lblFaculty = new javax.swing.JLabel();
        lblExternalResources = new javax.swing.JLabel();
        lblHumanity = new javax.swing.JLabel();
        lblRSyntaxTextArea = new javax.swing.JLabel();
        lblAutoComplete = new javax.swing.JLabel();
        lblJTattoo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        cmdOk = new javax.swing.JButton();
        cmdLicense = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("about_program");
        setResizable(false);

        lblVersion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVersion.setText(DrMIPS.PROGRAM_NAME + " " + DrMIPS.VERSION);

        lblIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/icons/icon_medium.png"))); // NOI18N

        lblAuthor.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblAuthor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAuthor.setText("by_author");

        lblDissertation.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblDissertation.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDissertation.setText("for_dissertation");

        lblFaculty.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblFaculty.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFaculty.setText("Faculdade de Engenharia da Universidade do Porto");

        lblExternalResources.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblExternalResources.setText("external_resources:");

        lblHumanity.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblHumanity.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHumanity.setText("Humanity Icons (https://launchpad.net/humanity/)");

        lblRSyntaxTextArea.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblRSyntaxTextArea.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRSyntaxTextArea.setText("RSyntaxTextArea (http://fifesoft.com/rsyntaxtextarea/)");

        lblAutoComplete.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblAutoComplete.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAutoComplete.setText("AutoComplete (http://fifesoft.com/autocomplete/)");

        lblJTattoo.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblJTattoo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJTattoo.setText("JTattoo (http://www.jtattoo.net/)");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblRSyntaxTextArea, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblIcon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblHumanity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblExternalResources, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblFaculty, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblAuthor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblVersion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblAutoComplete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblJTattoo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblDissertation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblVersion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAuthor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblDissertation)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblFaculty)
                .addGap(24, 24, 24)
                .addComponent(lblExternalResources)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblHumanity)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblRSyntaxTextArea)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAutoComplete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblJTattoo)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        cmdOk.setText("ok");
        cmdOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdOkActionPerformed(evt);
            }
        });
        jPanel2.add(cmdOk);

        cmdLicense.setText("license");
        cmdLicense.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdLicenseActionPerformed(evt);
            }
        });
        jPanel2.add(cmdLicense);

        getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdOkActionPerformed
		dispose();
    }//GEN-LAST:event_cmdOkActionPerformed

    private void cmdLicenseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdLicenseActionPerformed
		String license = "DrMIPS - Educational MIPS simulator\n" +
			"Copyright (C) 2013 Bruno Nova <ei08109@fe.up.pt>\n" +
			"\n" +
			"This program is free software: you can redistribute it and/or modify\n" +
			"it under the terms of the GNU General Public License as published by\n" +
			"the Free Software Foundation, either version 3 of the License, or\n" +
			"(at your option) any later version.\n" +
			"\n" +
			"This program is distributed in the hope that it will be useful,\n" +
			"but WITHOUT ANY WARRANTY; without even the implied warranty of\n" +
			"MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the\n" +
			"GNU General Public License for more details.\n" +
			"\n" +
			"You should have received a copy of the GNU General Public License\n" +
			"along with this program.  If not, see <http://www.gnu.org/licenses/>.";
		JOptionPane.showMessageDialog(this, license, Lang.t("license"), JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_cmdLicenseActionPerformed

	/**
	 * Translates the form's strings.
	 */
	protected final void translate() {
		setTitle(Lang.t("about_program", DrMIPS.PROGRAM_NAME));
		Lang.tButton(cmdOk, "ok");
		Lang.tButton(cmdLicense, "license");
		lblAuthor.setText(Lang.t("by_author", "Bruno Nova <ei08109@fe.up.pt>"));
		lblExternalResources.setText(Lang.t("external_resources") + ":");
		lblDissertation.setText(Lang.t("for_dissertation"));
	}
	
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdLicense;
    private javax.swing.JButton cmdOk;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblAuthor;
    private javax.swing.JLabel lblAutoComplete;
    private javax.swing.JLabel lblDissertation;
    private javax.swing.JLabel lblExternalResources;
    private javax.swing.JLabel lblFaculty;
    private javax.swing.JLabel lblHumanity;
    private javax.swing.JLabel lblIcon;
    private javax.swing.JLabel lblJTattoo;
    private javax.swing.JLabel lblRSyntaxTextArea;
    private javax.swing.JLabel lblVersion;
    // End of variables declaration//GEN-END:variables
}
