/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.feup.brunonova.drmips.gui;

/**
 *
 * @author bruno
 */
public class DlgSupportedInstructions extends javax.swing.JDialog {
	/** Index of the instructions tab. */
	private static final int INSTRUCTIONS_INDEX = 0;
	/** Index of the pseudo-instructions tab. */
	private static final int PSEUDO_INSTRUCTIONS_INDEX = 1;
	/** Index of the directives tab. */
	private static final int DIRECTIVES_INDEX = 2;
	
	/**
	 * Creates new form DlgSupportedInstructions
	 */
	public DlgSupportedInstructions(java.awt.Frame parent) {
		super(parent, false);
		initComponents();
		translate();
		getRootPane().setDefaultButton(cmdClose);
		Util.centerWindow(this);
		Util.enableCloseWindowWithEscape(this);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cmdClose = new javax.swing.JButton();
        pnlTabs = new javax.swing.JTabbedPane();
        pnlInstructions = new javax.swing.JScrollPane();
        pnlPseudoInstructions = new javax.swing.JScrollPane();
        pnlDirectives = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(450, 500));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        cmdClose.setText("close");
        cmdClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCloseActionPerformed(evt);
            }
        });
        jPanel1.add(cmdClose);

        getContentPane().add(jPanel1, java.awt.BorderLayout.SOUTH);

        pnlTabs.addTab("instructions", pnlInstructions);
        pnlTabs.addTab("pseudo_instructions", pnlPseudoInstructions);
        pnlTabs.addTab("directives", pnlDirectives);

        getContentPane().add(pnlTabs, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
		close();
    }//GEN-LAST:event_formWindowClosing

    private void cmdCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCloseActionPerformed
		close();
    }//GEN-LAST:event_cmdCloseActionPerformed

	/**
	 * Translates the dialog's strings.
	 */
	protected final void translate() {
		setTitle(Lang.t("instructions_supported_by_cpu"));
		Lang.tButton(cmdClose, "close");
		pnlTabs.setTitleAt(INSTRUCTIONS_INDEX, Lang.t("instructions"));
		pnlTabs.setTitleAt(PSEUDO_INSTRUCTIONS_INDEX, Lang.t("pseudo_instructions"));
		pnlTabs.setTitleAt(DIRECTIVES_INDEX, Lang.t("directives"));
	}
	
	/**
	 * Closes the window.
	 */
	private void close() {
		setVisible(false);
	}
	
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdClose;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane pnlDirectives;
    private javax.swing.JScrollPane pnlInstructions;
    private javax.swing.JScrollPane pnlPseudoInstructions;
    private javax.swing.JTabbedPane pnlTabs;
    // End of variables declaration//GEN-END:variables
}
