/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.feup.brunonova.drmips.gui;

import org.feup.brunonova.drmips.mips.CPU;

/**
 *
 * @author bruno
 */
public class DlgStatistics extends javax.swing.JDialog {
	/**
	 * Creates new form DlgStatistics
	 */
	public DlgStatistics(java.awt.Frame parent) {
		super(parent, false);
		initComponents();
		translate();
		getRootPane().setDefaultButton(cmdClose);
		Util.centerWindow(this);
		Util.enableCloseWindowWithEscape(this);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblClockPeriod = new javax.swing.JLabel();
        lblClockPeriodVal = new javax.swing.JLabel();
        lblClockFrequency = new javax.swing.JLabel();
        lblClockFrequencyVal = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        cmdClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        lblClockPeriod.setText("clock_period:");

        lblClockPeriodVal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblClockPeriodVal.setText("0");

        lblClockFrequency.setText("clock_frequency:");

        lblClockFrequencyVal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblClockFrequencyVal.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblClockPeriod, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblClockFrequency, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblClockPeriodVal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblClockFrequencyVal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblClockPeriod)
                    .addComponent(lblClockPeriodVal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblClockFrequency)
                    .addComponent(lblClockFrequencyVal))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        cmdClose.setText("close");
        cmdClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCloseActionPerformed(evt);
            }
        });
        jPanel2.add(cmdClose);

        getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCloseActionPerformed
		close();
    }//GEN-LAST:event_cmdCloseActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
		close();
    }//GEN-LAST:event_formWindowClosing

	/**
	 * Closes the window.
	 */
	private void close() {
		setVisible(false);
	}
	
	/**
	 * Translates the dialog's strings.
	 */
	protected void translate() {
		setTitle(Lang.t("statistics"));
		Lang.tButton(cmdClose, "close");
		lblClockPeriod.setText(Lang.t("clock_period") + ":");
		lblClockFrequency.setText(Lang.t("clock_frequency") + ":");
	}
	
	/**
	 * Refreshes the values.
	 * @param cpu CPU from where to get the statistics.
	 */
	protected void refresh(CPU cpu) {
		lblClockPeriodVal.setText(cpu.getClockPeriod() + " " + CPU.LATENCY_UNIT);
		lblClockFrequencyVal.setText(cpu.getClockFrequencyInAdequateUnit());
	}
	
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdClose;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblClockFrequency;
    private javax.swing.JLabel lblClockFrequencyVal;
    private javax.swing.JLabel lblClockPeriod;
    private javax.swing.JLabel lblClockPeriodVal;
    // End of variables declaration//GEN-END:variables
}
